# Generated by Django 2.2.6 on 2019-12-06 10:37

import django.core.validators
from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=48)),
                ('contact_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be upto 10 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField()),
                ('company_website', models.URLField()),
                ('company_logo', models.ImageField(default='', upload_to='images/', validators=[myapp.validators.validate_file_extension])),
                ('company_address', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=20)),
                ('company_pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
    ]
