# Generated by Django 2.2.6 on 2019-12-06 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be upto 10 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
