# Generated by Django 2.2.6 on 2019-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191206_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.TextField(),
        ),
    ]
