# Generated by Django 2.2.6 on 2019-12-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191206_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
