# Generated by Django 2.2.6 on 2019-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('company_logo', models.ImageField(default='', upload_to='images/')),
                ('company_address', models.CharField(max_length=72)),
                ('company_location', models.CharField(max_length=20)),
                ('company_pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
