# Generated by Django 2.2.6 on 2019-12-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_companylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='description',
            field=models.CharField(max_length=48),
        ),
    ]
