# Generated by Django 2.2.6 on 2019-12-09 09:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191209_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='company_website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companylist',
            name='contact_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be upto 10 digits', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='company_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companylist',
            name='company_pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
