# Generated by Django 2.2.6 on 2019-12-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191209_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyList',
            new_name='Company',
        ),
    ]
