# Generated by Django 2.2.6 on 2019-12-09 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20191209_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be upto 10 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('note', models.CharField(max_length=48)),
                ('designation', models.CharField(choices=[('hr', 'HR'), ('admin', 'ADMIN'), ('accountant', 'ACCOUNTANT'), ('sales manager', 'SALES MANAGER')], max_length=32)),
                ('employee_email', models.EmailField(max_length=254)),
                ('company_name', models.ForeignKey(null=True, on_delete=True, to='myapp.Company')),
            ],
        ),
    ]
