# Generated by Django 2.2.6 on 2020-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20191218_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_map',
            field=models.URLField(default='https://maps.google.com/maps?q=mohali&t=&z=13&ie=UTF8&iwloc=&output=embed', max_length=400),
        ),
    ]
