# Generated by Django 2.2.6 on 2020-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_company_company_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_map',
            field=models.TextField(),
        ),
    ]
