# Generated by Django 2.2.6 on 2020-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200106_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_map',
            field=models.URLField(default='https://maps.google.com/maps?q=mohali&t=&z=13&ie=UTF8&iwloc=&output=embed', max_length=400),
        ),
    ]
