# Generated by Django 2.2.6 on 2020-01-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200106_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_map',
            field=models.URLField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('website_company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company')),
                ('website_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.WebsiteType')),
            ],
        ),
    ]
