# Generated by Django 2.2.6 on 2020-01-07 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200106_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=32)),
                ('location_address', models.CharField(max_length=500)),
                ('location_city', models.CharField(max_length=32)),
                ('location_postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('location_country', models.CharField(max_length=32)),
                ('location_bussiness_hours', models.CharField(max_length=32)),
                ('is_headquater', models.CharField(max_length=32)),
                ('is_off_hours_accessible', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(null=True, on_delete=True, to='myapp.Company')),
            ],
        ),
    ]
