# Generated by Django 2.2.6 on 2020-01-07 07:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
