# Generated by Django 2.2.6 on 2020-01-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20200107_0745'),
        ('myapp', '0021_auto_20200107_0709'),
    ]

    operations = [
    ]
