# Generated by Django 2.2.6 on 2020-01-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_merge_20200107_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_headquater',
            field=models.BooleanField(default=False),
        ),
    ]
