# Generated by Django 2.2.6 on 2020-01-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200107_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_pincode',
        ),
    ]
