# Generated by Django 2.2.6 on 2020-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200107_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
