# Generated by Django 2.2.6 on 2020-01-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200107_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
    ]
