# Generated by Django 2.2.6 on 2020-01-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20200107_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='company_id',
            new_name='company_name',
        ),
    ]
