# Generated by Django 2.2.6 on 2020-01-07 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20200107_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='company_name',
        ),
        migrations.AddField(
            model_name='location',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Website'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='website',
            name='website_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.WebsiteType'),
        ),
    ]
