# Generated by Django 2.2.6 on 2020-01-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200107_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_country',
            new_name='countries',
        ),
    ]
