# Generated by Django 2.2.6 on 2020-01-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200107_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
    ]
