# Generated by Django 2.2.6 on 2020-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='', max_length=48),
        ),
    ]
