# Generated by Django 2.2.6 on 2020-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20200108_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='countries',
            field=models.CharField(max_length=32),
        ),
    ]
