# Generated by Django 2.2.6 on 2020-01-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20200108_1249'),
        ('myapp', '0033_auto_20200108_1001'),
    ]

    operations = [
    ]
