# Generated by Django 2.2.6 on 2020-01-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20200113_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_type_name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_name', models.CharField(max_length=32)),
                ('licence_quantity', models.CharField(max_length=500)),
                ('licence_key', models.CharField(max_length=200)),
                ('aquisition_date', models.DateField()),
                ('activation_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('note', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company')),
                ('licence_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.LicenceType')),
            ],
        ),
    ]
