# Generated by Django 2.2.6 on 2020-01-14 06:41

from django.db import migrations, models
import django.db.models.deletion
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20200113_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=48)),
                ('content', models.CharField(max_length=48)),
                ('file_upload', models.FileField(upload_to='documents/', validators=[myapp.validators.validate_file1_extension])),
                ('compani_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companie', to='myapp.Company')),
                ('document_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Document_category')),
            ],
        ),
    ]
