# Generated by Django 2.2.6 on 2020-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_licence_licencetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='note',
            new_name='licence_note',
        ),
        migrations.AlterField(
            model_name='licence',
            name='licence_name',
            field=models.CharField(max_length=50),
        ),
    ]
