# Generated by Django 2.2.6 on 2020-01-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20200114_0637'),
        ('myapp', '0037_document_category_documents'),
    ]

    operations = [
    ]
