# Generated by Django 2.2.6 on 2020-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20200115_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='countries',
            field=models.CharField(max_length=32),
        ),
    ]
