# Generated by Django 2.2.6 on 2020-01-15 13:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20200115_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='countries',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
