# Generated by Django 2.2.6 on 2020-01-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_device_devicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.DeviceType'),
        ),
    ]
