# Generated by Django 2.2.6 on 2020-01-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20200116_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('connectwise_api', models.CharField(max_length=200)),
                ('moneris_api', models.CharField(max_length=500)),
            ],
        ),
    ]
