# Generated by Django 2.2.6 on 2020-01-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20200116_1003'),
        ('myapp', '0044_package'),
    ]

    operations = [
    ]
