# Generated by Django 2.2.6 on 2020-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20200117_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=32),
        ),
    ]
