# Generated by Django 2.2.6 on 2020-01-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_merge_20200116_1305'),
        ('myapp', '0047_company_package'),
    ]

    operations = [
    ]
