# Generated by Django 2.2.6 on 2020-01-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_website_is_headquater_website'),
        ('myapp', '0052_remove_user_last_activity'),
    ]

    operations = [
    ]
