# Generated by Django 2.2.6 on 2020-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_merge_20200123_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='connectwise_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='moneris_check',
            field=models.BooleanField(default=False),
        ),
    ]
