# Generated by Django 2.2.6 on 2020-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_auto_20200123_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='connectwise_api',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='moneris_api',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
