# Generated by Django 2.2.6 on 2020-02-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20200207_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(default='', max_length=400)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Documents')),
            ],
        ),
    ]
