# Generated by Django 2.2.6 on 2020-02-11 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_document_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('where', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('attendees', models.ManyToManyField(to='myapp.Employee')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
