# Generated by Django 2.2.6 on 2020-02-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='company_i',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
    ]
