# Generated by Django 2.2.6 on 2020-02-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_meeting_company_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
