# Generated by Django 2.2.6 on 2020-02-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_auto_20200211_0936'),
        ('myapp', '0059_auto_20200212_1211'),
    ]

    operations = [
    ]
