# Generated by Django 2.2.6 on 2020-03-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_merge_20200213_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Location'),
        ),
    ]
