# Generated by Django 2.2.6 on 2020-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_employee_emp_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
