# Generated by Django 2.2.6 on 2020-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_auto_20200302_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_password',
            field=models.CharField(max_length=10),
        ),
    ]
