# Generated by Django 2.2.6 on 2020-03-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_auto_20200302_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='workstation_asset_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='myapp.Device'),
        ),
    ]
